### ISSUE TITLE
First page

### ISSUE THREAD

**Issue by bullfest** [Plongy/Inda-Projekt#1]
We need a first page on the report.

What does it need?

**Comment by bullfest** [comment]
Pirate flag!

**Comment by bullfest** [comment]
Pirate ships!

**Comment by Plongy** [comment]
Swallows, preferably unladen ones

**Comment by bullfest** [comment]
Title: Pirates - A game for landlubbers to feel the breeze of seven seas

Alexander Viklund
August Falk

Pirates is a game where you face your friends in a fierce deathbattle. You control your own pirate ship and use its cannons to shoot down your foes.
